export const CATEGORIES = [
  { id: 'labor', label: { fr: "Échange de main d'oeuvre", ht: "Echanj mendèv" } },
  { id: 'land', label: { fr: "Prêt de terrains", ht: "Prete tè" } },
  { id: 'animals', label: { fr: "Animaux", ht: "Zannimo" } },
  { id: 'plants', label: { fr: "Plantes", ht: "Plant" } },
  { id: 'donations', label: { fr: "Dons", ht: "Don" } },
  { id: 'tools', label: { fr: "Outils", ht: "Zouti" } },
];

export const TRANSLATIONS = {
  fr: {
    appName: "Twokaj",
    offline: "Vous êtes hors ligne. Les données seront synchronisées une fois la connexion rétablie.",
    login: "Connexion",
    register: "Inscription",
    pseudo: "Pseudo",
    name: "Nom complet",
    address: "Adresse",
    phone: "Téléphone",
    email: "Email",
    password: "Mot de passe",
    categories: "Catégories d'échange",
    myAds: "Mes annonces",
    allAds: "Toutes les annonces",
    createAd: "Créer une annonce",
    search: "Rechercher",
    filter: "Filtrer",
    location: "Lieu",
    category: "Catégorie",
    date: "Date",
    proposition: "Proposition",
    demand: "Recherche",
    exchangeFor: "En échange de",
    period: "Période",
    availability: "Disponibilité",
    contactMe: "Mete m an kontak",
    letChat: "Ann fè yon ti koze",
    itWorks: "Sa mache !",
    notInterested: "Mwen pa enterese",
    closeAd: "Fermer l'annonce",
    share: "Partager",
    gallery: "Galerie",
    adminOnly: "Réservé aux administrateurs",
    language: "Haitian Creole",
    save: "Enregistrer",
    cancel: "Annuler",
    profilePhoto: "Photo de profil",
    adPhoto: "Photo de l'annonce",
    days: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
    months: ["Jan", "Fév", "Mar", "Avr", "Mai", "Juin", "Juil", "Août", "Sep", "Oct", "Nov", "Déc"],
  },
  ht: {
    appName: "Twokaj",
    offline: "Ou pa konekte. Done yo pral senkronize lè ou gen entènèt.",
    login: "Konekte",
    register: "Enskri",
    pseudo: "Psedo",
    name: "Non konplè",
    address: "Adrès",
    phone: "Telefòn",
    email: "Imèl",
    password: "Modpas",
    categories: "Kategori echanj",
    myAds: "Anons mwen yo",
    allAds: "Tout anons yo",
    createAd: "Kreye yon anons",
    search: "Chache",
    filter: "Filtre",
    location: "Kote",
    category: "Kategori",
    date: "Dat",
    proposition: "Pwopozisyon",
    demand: "Rechèch",
    exchangeFor: "An echanj pou",
    period: "Peryòd",
    availability: "Disponibilite",
    contactMe: "Mete m an kontak",
    letChat: "Ann fè yon ti koze",
    itWorks: "Sa mache !",
    notInterested: "Mwen pa enterese",
    closeAd: "Fèmen anons la",
    share: "Pataje",
    gallery: "Galri",
    adminOnly: "Pou administratè sèlman",
    language: "Français",
    save: "Anrejistre",
    cancel: "Anile",
    profilePhoto: "Foto pwofil",
    adPhoto: "Foto anons",
    days: ["Len", "Mad", "Mèk", "Jedi", "Van", "Sam", "Dim"],
    months: ["Jan", "Feb", "Mas", "Apr", "Me", "Jen", "Jiy", "Out", "Sep", "Okt", "Nov", "Des"],
  }
};
